pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: "1"))
    }
	
    environment {
        registryCredential = 'ecr:us-east-1:awscreds'
        appRegistry = '197383505749.dkr.ecr.us-east-1.amazonaws.com/appimg'
        vprofileRegistry = "https://197383505749.dkr.ecr.us-east-1.amazonaws.com"
        cluster = "vproprod"
        service = "vproappprodesvc"
    }

    stages {
        stage ('Deploy to Prod ECS') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }        
}
